import * as React from "react";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";
import RestoreIcon from "@mui/icons-material/Restore";
import FavoriteIcon from "@mui/icons-material/Favorite";
import ArchiveIcon from "@mui/icons-material/Archive";
import Paper from "@mui/material/Paper";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import Avatar from "@mui/material/Avatar";

import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { selectListEvent, selectListGift } from "../../store";
import { useAppDispatch } from "../../hooks";
import { getAllEvents, getAllGifts } from "../../store/ThunkCreator";
import { Button } from "@mui/material";
import { Gift } from "../Gift";

export function MultiActionAreaCard(props: any) {
  const { value: events } = useSelector(selectListGift);
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(getAllGifts("запрос"));
  }, []);
  const [value, setValue] = useState(0);
  const ref = React.useRef<HTMLDivElement>(null);
  // const [messages, setMessages] = useState(messageExamples);

  // useEffect(() => {
  //   (ref.current as HTMLDivElement).ownerDocument.body.scrollTop = 0;
  //   setMessages(refreshMessages());
  // }, [value, setMessages]);
  const handler = () => {
    // dispatch(createEvent("запрос"));
  };
  return (
    <div className="container mx-auto max-w-2xl pt-5">
      {/* { loading && <Loader /> }
      { error && <ErrorMessage error={error} /> } */}
      { events.map(event => <Gift event={event} key={event.id} />)}
      

      {/* {modal && <Modal title="Create new product" onClose={close}>
        <CreateProduct onCreate={createHandler} />
      </Modal>}

      <button
        className="fixed bottom-5 right-5 rounded-full bg-red-700 text-white text-2xl px-4 py-2"
        onClick={open}
      >+</button> */}
    </div>
  )
    }   

// const messageExamples: readonly MessageExample[] = [
//   {
//     primary: "Brunch this week?",
//     secondary:
//       "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Birthday Gift",
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: "/static/images/avatar/1.jpg",
//   },
//   {
//     primary: "Recipe to try",
//     secondary:
//       "I am try out this new BBQ recipe, I think this might be amazing",
//     person: "/static/images/avatar/2.jpg",
//   },
//   {
//     primary: "Yes!",
//     secondary: "I have the tickets to the ReactConf for this year.",
//     person: "/static/images/avatar/3.jpg",
//   },
//   {
//     primary: "Doctor's Appointment",
//     secondary:
//       "My appointment for the doctor was rescheduled for next Saturday.",
//     person: "/static/images/avatar/4.jpg",
//   },
//   {
//     primary: "Discussion",
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Summer BBQ",
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: "/static/images/avatar/1.jpg",
//   },
// ];

